export const formStyles = {
  urlRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 10,
  },
  urlInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#3a3a3a",
    backgroundColor: "#111",
    color: "#f0f0f0",
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    minHeight: 46,
    maxHeight: 140,
    textAlignVertical: "top",
  },
  pasteButton: {
    backgroundColor: "#3a3a3a",
    borderRadius: 8,
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  pasteButtonIcon: {
    fontSize: 18,
  },
  previewCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#151515",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2c2c2c",
    padding: 10,
    marginBottom: 12,
  },
  previewThumbnail: {
    width: 80,
    height: 45,
    borderRadius: 6,
    backgroundColor: "#0d0d0d",
  },
  previewInfo: {
    flex: 1,
    gap: 4,
  },
  previewTitle: {
    color: "#f0f0f0",
    fontWeight: "600",
    fontSize: 13,
  },
  previewMeta: {
    color: "#888",
    fontSize: 12,
  },
  optionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  optionsCol: {
    flex: 1,
  },
  button: {
    backgroundColor: "#646cff",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  buttonDisabled: {
    backgroundColor: "#3a3a4a",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: "#3a3a3a",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
  },
} as const;
