import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#0d0d0d",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  card: {
    width: "100%",
    maxWidth: 480,
    maxHeight: "90%",
    backgroundColor: "#1a1a1a",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#2c2c2c",
    padding: 28,
  },
  cardWide: {
    maxWidth: 920,
  },
  twoColumnRow: {
    flexDirection: "row",
    gap: 24,
  },
  twoColumnLeft: {
    flex: 1,
  },
  twoColumnRight: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#f0f0f0",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 13,
    color: "#a0a0a0",
    textAlign: "center",
    marginBottom: 24,
  },
  label: {
    fontSize: 12,
    color: "#888",
    marginBottom: 4,
  },
  urlRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  urlInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#3a3a3a",
    backgroundColor: "#111",
    color: "#f0f0f0",
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
  },
  pasteButton: {
    backgroundColor: "#3a3a3a",
    borderRadius: 8,
    width: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  pasteButtonIcon: {
    fontSize: 18,
  },
  previewCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#151515",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2c2c2c",
    padding: 10,
    marginBottom: 12,
  },
  previewThumbnail: {
    width: 80,
    height: 45,
    borderRadius: 6,
    backgroundColor: "#0d0d0d",
  },
  previewInfo: {
    flex: 1,
    gap: 4,
  },
  previewTitle: {
    color: "#f0f0f0",
    fontWeight: "600",
    fontSize: 13,
  },
  previewMeta: {
    color: "#888",
    fontSize: 12,
  },
  optionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  optionsCol: {
    flex: 1,
  },
  dropdownButton: {
    borderWidth: 1,
    borderColor: "#3a3a3a",
    backgroundColor: "#111",
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dropdownButtonText: {
    color: "#f0f0f0",
    fontSize: 14,
  },
  dropdownChevron: {
    color: "#888",
    fontSize: 12,
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  dropdownMenu: {
    width: "100%",
    maxWidth: 320,
    backgroundColor: "#1a1a1a",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3a3a3a",
    overflow: "hidden",
  },
  dropdownOption: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#2c2c2c",
  },
  dropdownOptionSelected: {
    backgroundColor: "#2a2a3a",
  },
  dropdownOptionText: {
    color: "#f0f0f0",
    fontSize: 14,
  },
  button: {
    backgroundColor: "#646cff",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  buttonDisabled: {
    backgroundColor: "#3a3a4a",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: "#3a3a3a",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
  },
  searchMessage: {
    fontSize: 12,
    color: "#a0a0a0",
    textAlign: "center",
    marginBottom: 10,
  },
  linkButton: {
    alignSelf: "center",
    marginTop: 14,
  },
  jobList: {
    marginTop: 10,
  },
  // Zeroes a marginTop that only makes sense when stacked below another element — used when the
  // clear-finished link or the job list is the first thing in the right column instead.
  flushTop: {
    marginTop: 0,
  },
  jobCard: {
    backgroundColor: "#151515",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#2c2c2c",
    padding: 14,
    marginBottom: 10,
    gap: 8,
  },
  jobHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  jobThumbnail: {
    width: 56,
    height: 32,
    borderRadius: 4,
    backgroundColor: "#0d0d0d",
  },
  jobHeaderInfo: {
    flex: 1,
    gap: 2,
  },
  jobTitle: {
    color: "#f0f0f0",
    fontWeight: "600",
    fontSize: 14,
  },
  jobDuration: {
    color: "#888",
    fontSize: 12,
  },
  jobActions: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  statusText: {
    flex: 1,
    color: "#a0a0a0",
    fontSize: 13,
  },
  collapseButton: {
    backgroundColor: "#2c2c2c",
    borderRadius: 6,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  collapseChevron: {
    color: "#ccc",
    fontSize: 16,
    fontWeight: "700",
  },
  progressWrapper: {
    width: "100%",
    position: "relative",
  },
  progressTrack: {
    width: "100%",
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2c2c2c",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#646cff",
    borderRadius: 4,
  },
  progressEtaBadge: {
    position: "absolute",
    right: 4,
    top: "50%",
    transform: [{ translateY: -8 }],
    backgroundColor: "rgba(13,13,13,0.75)",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  progressEtaText: {
    color: "#f0f0f0",
    fontSize: 10,
    fontWeight: "600",
  },
  debugBox: {
    width: "100%",
    backgroundColor: "#111",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2c2c2c",
    padding: 10,
    gap: 4,
  },
  debugLine: {
    color: "#888",
    fontSize: 12,
    fontFamily: Platform.OS === "web" ? "monospace" : undefined,
  },
  errorText: {
    color: "#ff6b6b",
    textAlign: "center",
    fontSize: 13,
  },
  downloadButton: {
    backgroundColor: "#2ecc71",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  downloadButtonText: {
    color: "#0a0a0a",
    fontWeight: "700",
    fontSize: 13,
  },
  linkText: {
    color: "#a0a0a0",
    textDecorationLine: "underline",
    fontSize: 13,
  },
  groupHeader: {
    color: "#a0a0a0",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    marginTop: 4,
  },
  playlistModal: {
    width: "100%",
    maxWidth: 480,
    height: "85%",
    backgroundColor: "#1a1a1a",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#3a3a3a",
    padding: 20,
    gap: 10,
  },
  playlistModalTitle: {
    color: "#f0f0f0",
    fontWeight: "700",
    fontSize: 16,
  },
  playlistEntryList: {
    flex: 1,
  },
  playlistEntryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
  },
  playlistEntryThumbnail: {
    width: 64,
    height: 36,
    borderRadius: 4,
    backgroundColor: "#0d0d0d",
  },
  playlistEntryInfo: {
    flex: 1,
    gap: 2,
  },
  playlistEntryTitle: {
    color: "#f0f0f0",
    fontSize: 13,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#3a3a3a",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#646cff",
    borderColor: "#646cff",
  },
  checkboxMark: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
});
